import { test, expect } from "@playwright/test";
import ExcelJS from "exceljs";
import * as XLSX from "xlsx";
import { readFile } from "node:fs/promises";
import { TURNOVER_HEADERS } from "../lib/turnover-contracts";
import { STRENGTH_FILE } from "../lib/strength-file";

async function sampleUpload() {
  const template = JSON.parse(await readFile(STRENGTH_FILE, "utf8"));
  const category = template.strengthStructure[0];
  const subcategory = category.subcategories[0];
  const designation = subcategory.designations[0];
  const data = [subcategory.subcategory, "KGM", "00001", "Sample Employee", designation.designation, "M", "Sunday", designation.grade, "A", designation.cadre, category.category, "2024-01-15"];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([["Employee turnover report"], [...TURNOVER_HEADERS], data]), "Employees");
  return { name: "sample-turnover.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) };
}

test("upload, refresh persistence, navigation, failed replacement, and Excel download", async ({ page }) => {
  const before = await readFile(STRENGTH_FILE);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Upload report", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles(await sampleUpload());
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByText("Saved in this browser. Available after refresh or reopening.", { exact: true })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "Status", exact: true })).toHaveCount(0);
  const designationButton = page.getByRole("button", { name: "View employees for BACK PROCESS INCHARGE, M-13, in Spinning-BlowRoom, BACKPROCESS", exact: true });
  await designationButton.click();
  const employeeDialog = page.getByRole("dialog", { name: "BACK PROCESS INCHARGE", exact: true });
  await expect(employeeDialog).toBeVisible();
  await expect(employeeDialog.getByRole("heading", { name: "Sample Employee", exact: true })).toBeVisible();
  await expect(employeeDialog.getByText("Emp # 00001", { exact: true })).toBeVisible();
  for (const header of TURNOVER_HEADERS.filter((header) => header !== "Employee Name" && header !== "Emp #")) await expect(employeeDialog.getByText(header, { exact: true })).toBeVisible();
  await employeeDialog.getByRole("textbox", { name: "Search designation employees" }).fill("nobody-matches");
  await expect(employeeDialog.getByRole("heading", { name: "No employees match your search" })).toBeVisible();
  await employeeDialog.getByRole("button", { name: "Clear search", exact: true }).click();
  await employeeDialog.getByRole("textbox", { name: "Search designation employees" }).fill("00001 Sunday");
  await expect(employeeDialog.getByRole("heading", { name: "Sample Employee", exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/employees-desktop.png", fullPage: false });
  await page.keyboard.press("Escape");
  await expect(employeeDialog).toHaveCount(0);
  await page.getByRole("button", { name: "View employees for ASSISTANT FOREMAN, M-11, in Spinning-BlowRoom, BACKPROCESS", exact: true }).click();
  await expect(page.getByRole("heading", { name: "No on-roll employees in this designation" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Sample Employee", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Close employee details", exact: true }).click();
  await page.getByRole("tab", { name: "Summary", exact: true }).click();
  const adminSummary = page.getByRole("region", { name: "Admin & HR summary", exact: true });
  const spinningSummary = page.getByRole("region", { name: "Spinning summary", exact: true });
  await expect(adminSummary.getByRole("button", { name: "Administration", exact: true })).toBeVisible();
  await expect(spinningSummary.getByRole("button")).toHaveCount(5);
  for (const name of ["Back Process", "Ring", "Autocone / Machcone / RC", "Spinning General / Lab", "Services"]) await expect(spinningSummary.getByRole("button", { name, exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/summary-desktop.png", fullPage: false });
  await adminSummary.getByRole("button", { name: "Finance", exact: true }).click();
  await expect(page.getByRole("tab", { name: "Strength", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("region", { name: "BACKPROCESS detailed strength", exact: true })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "HR & ADMIN detailed strength", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Show all subcategories", exact: true }).click();
  await page.screenshot({ path: "test-results/home-desktop.png", fullPage: false });
  await page.reload();
  await expect(page.getByText("Restored from this browser. Available after refresh or reopening.", { exact: true })).toBeVisible();
  await expect(page.getByText("sample-turnover.xlsx", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Configuration", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Strength Configuration", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Turnover report", exact: true }).click();
  await expect(page.getByText("sample-turnover.xlsx", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Upload new report" }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles({ name: "corrupt.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: Buffer.from("not a workbook") });
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report could not be processed" })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByText("sample-turnover.xlsx", { exact: true })).toBeVisible();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download Excel", exact: true }).click();
  const download = await downloaded;
  await expect(page.getByRole("dialog", { name: "Excel download started" })).toBeVisible();
  expect(download.suggestedFilename()).toMatch(/\.xlsx$/);
  const path = await download.path();
  const downloadedBytes = await readFile(path!);
  const excel = new ExcelJS.Workbook();
  await excel.xlsx.readFile(path!);
  expect(Buffer.from(excel.getImage(0).buffer!)).toEqual(await readFile("public/kohinoor-logo.png"));
  const wb = XLSX.read(downloadedBytes, { type: "buffer" });
  const summaryRows = XLSX.utils.sheet_to_json<string[]>(wb.Sheets.Summary, { header: 1 });
  expect(summaryRows.some((row) => row[0] === "Spinning")).toBe(true);
  expect(summaryRows.some((row) => row[0] === "Administration")).toBe(true);
  expect(wb.SheetNames).toContain("Employees");
  expect(wb.SheetNames).toContain("Strength Detail");
  expect(wb.Sheets.Employees.C5.v).toBe("00001");
  for (const sheet of Object.values(wb.Sheets)) expect(XLSX.utils.sheet_to_json<string[]>(sheet, { header: 1 })[3].some((header) => /status/i.test(String(header)))).toBe(false);
  expect(errors).toEqual([]);
  expect(await readFile(STRENGTH_FILE)).toEqual(before);
});

test("mobile report and dialogs fit the viewport; configuration staging has clear success feedback", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.screenshot({ path: "test-results/upload-mobile.png", fullPage: false });
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles(await sampleUpload());
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/home-mobile.png", fullPage: false });
  await page.getByRole("button", { name: "View employees for BACK PROCESS INCHARGE, M-13, in Spinning-BlowRoom, BACKPROCESS", exact: true }).click();
  const mobileDialog = page.getByRole("dialog", { name: "BACK PROCESS INCHARGE", exact: true });
  await expect(mobileDialog.getByRole("heading", { name: "Sample Employee", exact: true })).toBeVisible();
  expect(await mobileDialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: "test-results/employees-mobile.png", fullPage: false });
  await mobileDialog.getByRole("button", { name: "Close employee details", exact: true }).click();
  await page.getByRole("link", { name: "Configuration", exact: true }).click();
  await page.getByRole("button", { name: "Add category", exact: true }).click();
  await page.getByRole("textbox", { name: "Category name" }).fill("TEST CATEGORY");
  await page.getByRole("dialog", { name: "Add category", exact: true }).getByRole("button", { name: "Add category", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Category added" })).toBeVisible();
  await expect(page.getByText("Your change is ready. Select Save changes at the top of the page to save it to the strength configuration.")).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByText("Unsaved changes", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.route("**/config", (route) => route.request().method() === "POST" ? route.abort() : route.continue());
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Configuration could not be saved" })).toBeVisible();
  await expect(page.getByText("Your changes remain on this page. Try Save changes again before leaving or refreshing.")).toBeVisible();
});

test("identical designation names in different subcategories show only their own employees", async ({ page }) => {
  const wb = XLSX.utils.book_new();
  const records = [
    ["Spinning-BlowRoom", "KGM", "101", "Blowroom Employee", "FITTER", "M", "Sunday", "E-03", "A", "Worker", "BACKPROCESS", "2024-01-15"],
    ["SPINNING - CARD ROOM", "KGM", "102", "Cardroom Employee", "FITTER", "M", "Friday", "E-03", "B", "Worker", "BACKPROCESS", "2025-02-01"],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[...TURNOVER_HEADERS], ...records]), "Employees");
  await page.goto("/");
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles({ name: "scoped-employees.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) });
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await page.getByRole("button", { name: "View employees for FITTER, E-03, in Spinning-BlowRoom, BACKPROCESS", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Blowroom Employee", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Cardroom Employee", exact: true })).toHaveCount(0);
  await page.getByRole("textbox", { name: "Search designation employees" }).fill("Cardroom Employee");
  await expect(page.getByRole("heading", { name: "No employees match your search" })).toBeVisible();
  await page.getByRole("button", { name: "Close employee details", exact: true }).click();
  await page.getByRole("button", { name: "View employees for FITTER, E-03, in SPINNING - CARD ROOM, BACKPROCESS", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Cardroom Employee", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Blowroom Employee", exact: true })).toHaveCount(0);
  await expect(page.getByRole("textbox", { name: "Search designation employees" })).toHaveValue("");
});

test("a failed current-data check prevents a stale export and preserves the scanned report", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles(await sampleUpload());
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  let downloads = 0;
  page.on("download", () => downloads++);
  await page.route("**/", (route) => route.request().method() === "POST" ? route.abort() : route.continue());
  await page.getByRole("button", { name: "Download Excel", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Download could not be prepared", exact: true })).toBeVisible();
  expect(downloads).toBe(0);
  await page.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByText("sample-turnover.xlsx", { exact: true })).toBeVisible();
  await page.unroute("**/");
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download Excel", exact: true }).click();
  await download;
});

test("department aliases and differing grades count employees, harmless duplicates are explained, and older saved scans reprocess", async ({ page }) => {
  const wb = XLSX.utils.book_new();
  const employee = ["Spinning - Ring - 5", "2", "501", "Ring Employee", "PIECER", "M", "Sunday", "M-99", "A", "Worker", "84", "2024-01-01"];
  const repeat = [...employee];
  repeat[8] = "B";
  repeat[6] = "Friday";
  repeat[7] = "";
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[...TURNOVER_HEADERS], employee, repeat]), "Employees");
  await page.goto("/");
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles({ name: "department-alias.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) });
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await page.getByRole("button", { name: "Review issues (1)", exact: true }).click();
  await expect(page.getByText("Counted once", { exact: true })).toBeVisible();
  await expect(page.getByText("Excluded from on-roll", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Close validation notes", exact: true }).click();
  await page.getByRole("navigation", { name: "Report categories", exact: true }).getByRole("button", { name: "RING", exact: true }).click();
  const designation = page.getByRole("button", { name: "View employees for PIECER, E-03, in RING-5 - PRODUCTION, RING", exact: true });
  await designation.click();
  await expect(page.getByRole("heading", { name: "Ring Employee", exact: true })).toBeVisible();
  await expect(page.getByText("M-99", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Close employee details", exact: true }).click();
  await page.evaluate(() => new Promise<void>((resolve, reject) => {
    const request = indexedDB.open("kohinoor-turnover", 1);
    request.onerror = () => reject(request.error);
    request.onsuccess = () => {
      const db = request.result;
      const transaction = db.transaction("reports", "readwrite");
      const store = transaction.objectStore("reports");
      const saved = store.get("latest");
      saved.onsuccess = () => { const previous = saved.result; previous.result.matchingVersion = 0; store.put(previous, "latest"); };
      transaction.oncomplete = () => { db.close(); resolve(); };
      transaction.onerror = () => reject(transaction.error);
    };
  }));
  await page.reload();
  await expect(page.getByRole("dialog", { name: "Saved upload reprocessed", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await page.getByRole("navigation", { name: "Report categories", exact: true }).getByRole("button", { name: "RING", exact: true }).click();
  await designation.click();
  await expect(page.getByRole("heading", { name: "Ring Employee", exact: true })).toBeVisible();
});

test("restored Strength tables show positive vacancies green and negative vacancies red", async ({ page }) => {
  const template = JSON.parse(await readFile(STRENGTH_FILE, "utf8"));
  const category = template.strengthStructure[0];
  const subcategory = category.subcategories[0];
  const designation = subcategory.designations[0];
  const positive = subcategory.designations.find((item: { designation: string; approvedStrength: number }) => item.designation !== designation.designation && item.approvedStrength > 0);
  const wb = XLSX.utils.book_new();
  const employees = Array.from({ length: designation.approvedStrength + 1 }, (_, index) => [subcategory.subcategory, "KGM", String(700 + index), `Employee ${index}`, designation.designation, "M", "Sunday", designation.grade, "A", designation.cadre, category.category, "2024-01-01"]);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[...TURNOVER_HEADERS], ...employees]), "Employees");
  await page.goto("/");
  await page.getByRole("button", { name: "Upload report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles({ name: "vacancy-colours.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) });
  await page.getByRole("button", { name: "Start scanning" }).click();
  await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByRole("navigation", { name: "Report categories", exact: true })).toBeVisible();
  const vacancy = (item: { designation: string; grade: string }) => page.getByRole("button", { name: `View employees for ${item.designation}, ${item.grade}, in ${subcategory.subcategory}, ${category.category}`, exact: true }).locator("xpath=ancestor::tr").locator('[data-label="Vacancies"]');
  await expect(vacancy(designation)).toHaveText("-1");
  await expect(vacancy(designation)).toHaveClass(/text-red-700/);
  await expect(vacancy(positive)).toHaveClass(/text-emerald-700/);
  await page.screenshot({ path: "test-results/strength-restored-desktop.png", fullPage: false });
});

test("designation-level cases clear negative vacancy with designation, Social Security and Other", async ({ page }) => {
  const historyBefore = await readFile("../strength-adjustment.json", "utf8");
  const templateBefore = await readFile(STRENGTH_FILE, "utf8");
  const template = JSON.parse(templateBefore);
  const category = template.strengthStructure[0];
  const subcategory = category.subcategories[0];
  const designation = subcategory.designations[0];
  const target = subcategory.designations.find((item: { designation: string }) => item.designation !== designation.designation);
  const wb = XLSX.utils.book_new();
  const employees = Array.from({ length: designation.approvedStrength + 3 }, (_, index) => [subcategory.subcategory, "KGM", String(900 + index), `Review Employee ${index}`, designation.designation, "M", "Sunday", "M-99", "A", designation.cadre, category.category, "2024-01-01"]);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([[...TURNOVER_HEADERS], ...employees]), "Employees");
  const upload = { name: "review-cases.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buffer: XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) };
  const saved: Record<string, unknown>[] = [];
  let historyResponse = "";
  let failSave = false;
  let historyError = false;
  await page.route("**/*", async (route) => {
    const request = route.request();
    if (request.method() !== "POST" || !request.headers()["next-action"]) return route.continue();
    const body = request.postData() ?? "";
    if (body.includes('"caseType"')) {
      if (failSave) return route.abort();
      const resolution = JSON.parse(body)[0];
      expect(resolution.employeeId).toBeUndefined();
      saved.push(resolution);
      return route.fulfill({ status: 200, contentType: "text/x-component", body: historyResponse.replace(/^1:\[\]/m, `1:${JSON.stringify({ ok: true, resolution })}`) });
    }
    const response = await route.fetch();
    const text = await response.text();
    if (/^1:\[\]/m.test(text)) {
      historyResponse = text;
      return route.fulfill({ response, body: text.replace(/^1:\[\]/m, `1:${JSON.stringify(historyError ? { error: "Case history could not be read. The existing history has been preserved; restore a valid strength-adjustment.json before saving cases." } : saved)}`) });
    }
    return route.fulfill({ response });
  });
  const uploadWorkbook = async () => {
    await page.getByRole("button", { name: /Upload (new )?report/, exact: true }).click();
    await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles(upload);
    await page.getByRole("button", { name: "Start scanning" }).click();
    await expect(page.getByRole("dialog", { name: "Report ready", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Got it" }).click();
  };
  await page.goto("/");
  await uploadWorkbook();
  const vacancy = page.getByRole("button", { name: `View employees for ${designation.designation}, ${designation.grade}, in ${subcategory.subcategory}, ${category.category}`, exact: true }).locator("xpath=ancestor::tr").locator('[data-label="Vacancies"]');
  await expect(vacancy).toHaveText("-3");
  await page.getByRole("button", { name: "Review cases", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Review Cases", exact: true });
  await expect(dialog.locator("article")).toHaveCount(1);
  await expect(dialog.getByTestId("designation-case")).toHaveCount(3);
  await expect(dialog.getByText(/Review Employee/)).toHaveCount(0);
  await expect(dialog.getByRole("combobox")).toHaveCount(3);
  const first = dialog.getByTestId("designation-case").nth(0);
  const second = dialog.getByTestId("designation-case").nth(1);
  const third = dialog.getByTestId("designation-case").nth(2);
  await first.getByRole("combobox").selectOption(`post:${target.designation}`);
  await first.getByRole("button", { name: "Save case", exact: true }).click();
  await expect(first.getByText(`Against Post ? ${target.designation} ? Saved`, { exact: true })).toBeVisible();
  await expect(dialog.getByText("Vacancy: -2", { exact: true })).toBeVisible();
  await second.getByRole("combobox").selectOption("__social_security__");
  await second.getByRole("button", { name: "Save case", exact: true }).click();
  await expect(dialog.getByText("Vacancy: -1", { exact: true })).toBeVisible();
  await third.getByRole("combobox").selectOption("__other__");
  await expect(third.getByRole("button", { name: "Save case", exact: true })).toBeDisabled();
  await third.getByRole("textbox").fill("Temporary duty");
  failSave = true;
  await third.getByRole("button", { name: "Save case", exact: true }).click();
  await expect(third.getByRole("button", { name: "Save case", exact: true })).toBeEnabled();
  await expect(dialog.getByText("Vacancy: -1", { exact: true })).toBeVisible();
  failSave = false;
  await third.getByRole("button", { name: "Save case", exact: true }).click();
  await expect(dialog.getByText("Vacancy: 0", { exact: true })).toBeVisible();
  await expect(third.getByText("Other ? Temporary duty ? Saved", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/review-cases-desktop.png", fullPage: false });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/review-cases-mobile.png", fullPage: false });
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.getByRole("button", { name: "Close review cases" }).click();
  await expect(vacancy).toHaveText("0");
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download Excel", exact: true }).click();
  const path = await (await downloaded).path();
  const excel = XLSX.read(await readFile(path!), {type:"buffer"});
  expect(excel.Sheets["Strength Detail"].H5.v).toBe(0);
  expect(excel.Sheets["Strength Detail"].M5.v).toBe(-3);
  expect(excel.Sheets["Review Cases Adjustments"].F7.v).toBe("Temporary duty");
  await page.getByRole("button", { name: "Got it", exact: true }).click();
  await page.reload();
  await expect(vacancy).toHaveText("0");
  await uploadWorkbook();
  await expect(vacancy).toHaveText("-3");
  await page.getByRole("button", { name: "Review cases", exact: true }).click();
  await expect(dialog.getByText("Previous Match Found", { exact: true })).toHaveCount(3);
  await expect(dialog.getByText(/? Saved$/, { exact: false })).toHaveCount(0);
  await first.getByRole("button", { name: "Apply", exact: true }).click();
  await expect(dialog.getByText("Vacancy: -2", { exact: true })).toBeVisible();
  await second.getByRole("button", { name: "Change", exact: true }).click();
  await second.getByRole("combobox").selectOption("__other__");
  await second.getByRole("textbox").fill("Training duty");
  await second.getByRole("button", { name: "Save case", exact: true }).click();
  await expect(dialog.getByText("Vacancy: -1", { exact: true })).toBeVisible();
  await third.getByRole("button", { name: "Apply", exact: true }).click();
  await expect(dialog.getByText("Vacancy: 0", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Close review cases" }).click();
  historyError = true;
  await page.getByRole("button", { name: "Upload new report", exact: true }).click();
  await page.getByLabel("Turnover workbook", { exact: true }).setInputFiles(upload);
  await page.getByRole("button", { name: "Start scanning" }).click();
  const failure = page.getByRole("dialog", { name: "Report could not be processed", exact: true });
  await expect(failure).toBeVisible();
  await expect(failure.getByText(/restore a valid strength-adjustment.json/)).toBeVisible();
  await failure.getByRole("button", { name: "Got it", exact: true }).click();
  await expect(vacancy).toHaveText("0");
  expect(await readFile("../strength-adjustment.json", "utf8")).toBe(historyBefore);
  expect(await readFile(STRENGTH_FILE, "utf8")).toBe(templateBefore);
});
